src/common/defines/kmpmp_00_defines.txt
Attrition decrease by 40%
min 0.04 to 0.024
amx from 12 to 0.72
=> Lower Attrition

src/common/commander_orders/kmpmp_01_convoy_raiding.txt, src/common/defines/kmpmp_00_defines.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
Convoy Raiding only possible with 20 or more ships
Convoy raiding rebalanced
=> Navy Balance

src/common/decisions/kmpmp_country_decisions.txt, src/common/history/global/kmpmp_global.txt, src/common/interest_group_traits/kmpmp_00_landed_interest_traits.txt, src/common/journal_entries/kmpmp_00_sick_man.txt, src/common/modifiers/kmpmp_italy_buff_modifiers.txt, src/common/modifiers/kmpmp_japan_buff_modifiers.txt, src/common/modifiers/kmpmp_mexico_buff_modifiers.txt, src/common/modifiers/kmpmp_nation_decision_modifiers.txt, src/common/modifiers/kmpmp_ottoman_buff_modifiers.txt, src/events/00_kmpmp_italian_unification.txt, src/events/00_kmpmp_sick_man_events.txt, src/events/kmpmp_mexico_buff_events.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
=> add new nation buffs

src/common/production_method_groups/kmpmp_01_industry.txt, src/common/production_methods/kmpmp_01_industry.txt, src/common/production_methods/kmpmp_09_misc_resource.txt
=> adjust pms

src/common/decrees/kmpmp_decrees.txt, src/common/modifiers/kmpmp_static_modifiers.txt
=> add bonus for authority excess - remove enlistment decree changes

README.md, src/common/company_types/00_kmpmp_companies.txt, src/common/laws/kmpmp_economic_system.txt, src/common/laws/kmpmp_trade_policy.txt
-> Move +1 Company Slot from LF -> Free Trade
Company changes:
Flavored comps:
Sweden
Ericsson: +10% inno -> 15% inno / +5% WEA -> 1% WEA
LKAB: add Coalmines as effected building
Argentina:
Bunge & Born: 20% Rural Folk -> 10% Livestock Ranches throughput / 10% tooling TP -> 15%
Ferrocarril Central Córdoba : add steel Mills as Building 5% -> 10% 10% Livestock Ranches throughput
Bolivia
Compañía de Salitres y Ferrocarril de Antofagasta : 5% Infra -> 10% Infra
Estañífera de Llallagua: add Iron Mines
Brazil:
São Paulo Railway Co. Ltd. 10 TPC -> 100
Amadeo Rossi & Cia.: add -5% Mil goods costs
Mexiko:
Fundidora de Fierro y Acero de Monterrey : 5% -> 15% Railway TP
Paraguay:
La Rosada: 10% ->15% Iron Mines TP
Peru:
Peruvian Amazon Company: add Toolshops Mortality shit -> 10% steel mill TP
USA: …
=> Company Changes

src/common/country_formation/kmpmp_formables.txt, src/common/decisions/kmpmp_country_decisions.txt, src/common/journal_entries/kmpmp_reino_unido.txt, src/common/on_actions/kmpmp_on_actions.txt
=> Issue 74 reinu unido protectorate diplo play decision

src/common/technology/technologies/kmpmp_social.txt
=> raise techs land_trade_cap

src/common/laws/kmpmp_education_system.txt, src/common/laws/kmpmp_health_system.txt, src/common/laws/kmpmp_internal_security.txt, src/common/laws/kmpmp_policing.txt, src/common/laws/qwf_army_model.txt
Education System
Private Schools: 0,5% -> 0,75% EA per Wealth
Local Police Force: -5% penalties from trumoil -> -10% / add +1 Max Law Enforcement institution investment
Army Model
Professional Army:
Conscription Center Max Level 50 -> 65
Unit experience gain: 25 -> 35%
National Militia:
Barracks Max Level: 5 -> 35
add Training rate 35%
add -5% mil goods costs
Unit experience gain: +5%
Mass Conscription:
Training rate: 100% -> 85%
Unit exp: -10%
Internal Security
Secret Police:
add -5% radicals from discrimination per lvl
Health System:
Charity Hospitals:
+1 Max Health System Institution
0.5 -> 0.75 Sol for lower strata
Public Health Ensurance:
0.5 Sol -> 0.3 Sol
Private Health Ensurance:
-0.2 Mortality per wealth -> -0.25
0.5 Sol -> 0.6 Sol for upper strate
add 0.3 Sol for middle strata
=> Law changes

src/common/journal_entries/kmpmp_00_corn_laws.txt
=> modify je_corn_law possible

src/common/decisions/kmpmp_player_boost_decisions.txt, src/common/modifier_types/kmpmp_modifier_types.txt, src/common/modifiers/kmpmp_player_boost_modifiers.txt, src/common/on_actions/kmpmp_on_actions.txt, src/common/scripted_effects/kmpmp_player_boost_effects.txt, src/localization/english/kmpmp_l_english.yml, src/localization/english/kmpmp_modifiers_l_english.yml, src/localization/german/kmpmp_l_german.yml, src/localization/german/kmpmp_modifiers_l_german.yml
=> Player buff rebalance

src/common/decisions/kmpmp_country_decisions.txt, src/common/on_actions/kmpmp_on_actions.txt
=> rebalance emser depeche

src/common/technology/technologies/kmpmp_social.txt
=> move plus 1 company from macroeconomics to central_planning

src/events/kmpmp_japan_buff_events.txt
=> adjust japan claims on siam to v1.5

src/common/history/global/kmpmp_country_buffs_global.txt, src/common/history/global/kmpmp_global.txt, src/common/modifiers/kmpmp_GP_debuff_modifiers.txt, src/common/modifiers/kmpmp_nation_buff_modifiers.txt, src/common/on_actions/kmpmp_on_actions.txt, src/common/scripted_effects/kmpmp_nation_buff_effects.txt
=> reapply nation buffs

src/common/laws/kmpmp_health_system.txt, src/common/modifier_types/kmpmp_00_modifier_types.txt
=> update private health insurence

src/common/modifier_types/kmpmp_00_modifier_types.txt, src/common/on_actions/kmpmp_on_actions.txt, src/events/00_kmpmp_sick_man_events.txt
=> fix sick man of europe

src/common/modifiers/kmpmp_nation_decision_modifiers.txt
=> fix united iberia buff

src/.metadata/metadata_kmpmp.json, src/.metadata/metadata_kspmp.json
=> update to 1.5.13

src/common/decisions/kmpmp_country_decisions.txt, src/common/modifiers/kmpmp_mexico_buff_modifiers.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
=> integrate mesoamericans peru/bolivia/federation

src/common/history/global/kmpmp_global.txt
=> Remove Ukrainian homeland state KUBAN

src/common/history/global/kmpmp_country_buffs_global.txt, src/common/modifiers/kmpmp_nation_buff_modifiers.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
add modifier 50% more unit defense offense
=> China buff

src/common/goods/kmpmp_00_goods.txt
=> Electricity no longer tradeable

src/common/journal_entries/kmpmp_00_sick_man.txt
=> Fix ottoman literacy tazimat

src/common/modifiers/kmpmp_ottoman_buff_modifiers.txt, src/common/on_actions/kmpmp_on_actions.txt, src/events/00_kmpmp_sick_man_events.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
Closes #129 
if tazimate completion fails - ottoman no longer gets unrecognized and gets buff multiplied by number of completed tazimates
=> rework ottoman tazimates

src/common/mobilization_options/GGGG_guns.txt
=> Force enable mobilization option firearms

src/common/country_formation/kmpmp_00_formable_countries.txt, src/common/country_formation/kmpmp_formables.txt
=> Form arabia only needs nationalism

src/common/country_formation/kmpmp_00_formable_countries.txt, src/common/history/interests/00_interests.txt
=> remove gb 3 interest regions

src/common/journal_entries/kmpmp_00_sick_man.txt
now needs 37.1% literacy to complete
Closes #187
=> ottoman literacy tazimate fix 2

src/common/laws/kmpmp_00_migration.txt
=> workaround migration

src/common/history/global/kmpmp_country_buffs_global.txt, src/common/scripted_effects/kmpmp_nation_buff_effects.txt
massive empire debuf removed
Closes #198
=> remove prussia debuff

src/common/history/global/kmpmp_regional_je_global.txt, src/common/journal_entries/kmpmp_regional_je.txt
add state Santo Domingo
Closes #201
=> fix je sugar monopoly

src/common/on_actions/kmpmp_on_actions.txt
=> fix queen victoria modifier

src/.metadata/metadata_kmpmp.json, src/.metadata/metadata_kspmp.json, src/common/commander_orders/kmpmp_01_convoy_raiding.txt, src/common/commander_orders/vtm_00_advance.txt, src/common/dynamic_country_names/00_kmpmp_dynamic_country_names.txt, src/common/on_actions/kmpmp_on_actions.txt, src/gui/outliner.gui, src/gui/outliner_framework.gui
=> update to 1.6.2

src/common/on_actions/kmpmp_on_actions.txt, src/common/scripted_effects/kmpmp_fix_effects.txt
=> fix migrated pops culture

src/common/decisions/kmpmp_country_decisions.txt
=> add pbc for decision "integrate the mesoamericans"

src/localization/german/replace/interfaces_l_german.yml
=> fix german loc in country diplomacy panel

src/common/scripted_effects/kmpmp_update_global_lists_effects.txt, src/common/scripted_triggers/kmpmp_united_country_triggers.txt
=> fix existing check for global lists

src/common/company_types/00_kmpmp_companies.txt, src/common/company_types/kmpmp_basic_companies.txt, src/common/company_types/kmpmp_companies.txt, src/localization/english/kmpmp_companies_l_english.yml, src/localization/english/replace/companies_l_english.yml, src/localization/german/kmpmp_companies_l_german.yml, src/localization/german/replace/companies_l_german.yml
=> company rebalance

src/common/modifiers/kmpmp_player_boost_modifiers.txt
State capitalism:
100 -> 150 Authority
10% -> 15% decree cost
10% -> 15% Manufacturing tax income
Military-Industrial Complex:
change 10% -> 15% gov wages
add -10% loyalists from SOL increase
add +10% radicals from SOL decrease
Autarky:
100 Authority -> 200
add -10% decree costs
Social& Welfare State:
change 15% gov wages -> 20%
add -10% company Throughput bonus
add -10% production tech speed
Tycoon capitalism:
add 10% company throuhput bonus
=> Agenda Rework

src/common/decisions/kmpmp_one_time_fixes_descisions.txt
=> one time fix ottoman annexes serbia

src/common/scripted_effects/kmpmp_nation_buff_effects.txt, src/events/00_kmpmp_sick_man_events.txt
=> allow ottoman paths if tazimates fail

src/common/script_values/kmpmp_sv.txt, src/common/script_values/zz_kmpmp_war_exhaustion_values.txt
=> war exhaustion only for incorporated occupied states

src/.metadata/metadata_kmpmp.json, src/.metadata/metadata_kmpmp_test.json, src/.metadata/metadata_kspmp.json, src/common/laws/kmpmp_00_slavery.txt
=> update to 1.7.5

src/common/scripted_effects/kmpmp_00_victoria_scripted_effects.txt, src/common/static_modifiers/kmpmp_character_modifiers.txt, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_l_german.yml
=> no loyalists and lowered legitimacy from abdication

src/common/power_bloc_identities/kmpmp_00_power_bloc_identities.txt, src/common/script_values/zz_kmpmp_00_diplomacy_values.txt, src/common/script_values/zz_kmpmp_01_power_bloc_values.txt, src/common/static_modifiers/kmpmp_00_code_static_modifiers.txt
=> adjusted power bloc mechanics

src/common/diplomatic_actions/kmpmp_31_power_bloc_force_regime_change.txt, src/common/modifier_type_definitions/kmpmp_00_modifier_types.txt, src/common/modifier_type_definitions/kmpmp_05_power_bloc_modifier_types.txt, src/common/modifier_type_definitions/kmpmp_06_country_modifier_types.txt, src/common/modifier_type_definitions/kmpmp_modifier_types.txt, src/common/power_bloc_identities/kmpmp_00_power_bloc_identities.txt, src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt, src/common/power_bloc_principles_groups.txt/kmpmp_00_power_bloc_principle_groups.txt, src/common/production_methods/kmpmp_06_urban_center.txt, src/common/production_methods/kmpmp_08_monuments.txt, src/common/production_methods/mrpa_railway.txt, src/common/script_values/kmpmp_war_support.txt, src/common/script_values/zz_kmpmp_01_power_bloc_values.txt, src/common/script_values/zz_kmpmp_war_exhaustion_values.txt, src/common/scripted_effects/kmpmp_00_victoria_scripted_effects.txt, src/localization/english/kmpmp_interfaces_l_english.yml, src/localization/english/kmpmp_modifiers_l_english.yml, src/localization/german/kmpmp_interfaces_l_german.yml, src/localization/german/kmpmp_modifiers_l_german.yml
=> adapt principles

src/common/history/global/kmpmp_global.txt, src/common/laws/kmpmp_00_distribution_of_power.txt, src/common/laws/kmpmp_00_economic_system.txt, src/common/laws/kmpmp_00_governance_principles.txt, src/common/laws/kmpmp_00_health_system.txt, src/common/laws/kmpmp_00_policing.txt, src/common/laws/kmpmp_00_trade_policy.txt
Nation changes:
Changed laws of the following Nations to Mercantilism:
GB, France, USA
TRADE POLICY
Free Trade:
added +200% (base) cost to Embargo
removed trade bureaucracy cost bonus
removed the company slot
Protectionism:
added +1 Company slot
Mercantilism:
-25% Trade Route Bureaucracy cost
+25% Trade Volume
ECONOMIC SYSTEM:
Laissez Faire:
changed private allocation from 75% to 70%
changed loan interest rate from -25% to -30%
changed capitalist/shopkeepers reinvestmen eff. from 25% to 30%
Industry Banned:
changed Agriculture and Plantations tp from 10% to 20%
changed Aristoxrats investement pool contribution efficency from 25% to +50%
lowered both tech mali to -10%
changed gov div reinvestment to efficency from 25% to 30%
changed gov div eff from 30% to 50%
added -10% pollution effects …
=> Law balance 1.7

src/common/laws/kmpmp_00_health_system.txt
=> fix private health insurance mortality modifier

src/common/laws/kmpmp_00_economic_system.txt
=> interventionism fix

src/common/defines/kmpmp_00_defines.txt, src/common/static_modifiers/kmpmp_00_code_static_modifiers.txt
=> bankruptcy rework

src/common/diplomatic_actions/kmpmp_10_alliance.txt, src/common/diplomatic_actions/kmpmp_11_defensive_pact.txt, src/common/diplomatic_actions/kmpmp_27_foreign_investment_agreement.txt, src/common/diplomatic_actions/kmpmp_27_foreign_investment_rights.txt, src/common/history/global/kmpmp_country_buffs_global.txt, src/common/journal_entries/kmpmp_china_buff_je.txt, src/common/on_actions/kmpmp_temporary_on_actions.txt, src/common/static_modifiers/kmpmp_china_buff_modifiers.txt, src/common/static_modifiers/kmpmp_nation_buff_modifiers.txt, src/localization/english/kmpmp_china_buff_l_english.yml, src/localization/english/kmpmp_l_english.yml, src/localization/german/kmpmp_china_buff_l_german.yml, src/localization/german/kmpmp_l_german.yml
=> china balance and china buff

src/gui/00_kmpmp_graph_tooltips.gui, src/gui/00_kmpmp_outliner_pinnable_types.gui, src/gui/kmpmp_graph_tooltips.gui, src/gui/kmpmp_outliner_pinnable_types.gui, src/gui/kmpmp_politics_panel_types.gui, src/localization/english/kmpmp_interfaces_l_english.yml, src/localization/german/kmpmp_interfaces_l_german.yml
=> add mods "GDP Plotline Plus", "Visual Shortage Fix"

src/common/laws/kmpmp_00_governance_principles.txt, src/common/script_values/kmpmp_sv.txt, src/common/scripted_effects/kmpmp_00_victoria_scripted_effects.txt, src/localization/english/kmpmp_script_values_l_english.yml, src/localization/english/kmpmp_triggers_l_english.yml, src/localization/german/kmpmp_script_values_l_german.yml, src/localization/german/kmpmp_triggers_l_german.yml
=> limit council republic

src/common/laws/kmpmp_00_governance_principles.txt, src/localization/english/kmpmp_triggers_l_english.yml, src/localization/german/kmpmp_triggers_l_german.yml
check ig leader ideologies for any interest group except trade unions
Closes #336
=> fix law council republic can_enact

src/common/decisions/kmpmp_player_boost_decisions.txt, src/common/laws/kmpmp_00_economic_system.txt, src/common/messages/kmpmp_player_boost_messages.txt, src/common/on_actions/kmpmp_on_actions.txt, src/common/on_actions/kmpmp_player_boost_on_actions.txt, src/common/scripted_effects/kmpmp_player_boost_effects.txt, src/common/scripted_triggers/kmpmp_player_boost_triggers.txt, src/common/static_modifiers/kmpmp_player_boost_modifiers.txt, src/localization/english/kmpmp_l_english.yml, src/localization/english/kmpmp_player_boost_l_english.yml, src/localization/german/kmpmp_l_german.yml, src/localization/german/kmpmp_player_boost_l_german.yml
- Rhine Capitalism
- Unite the workers of the World
Closes #298
=> New Agendas

src/common/scripted_effects/kmpmp_united_country_buff_effects.txt, src/common/scripted_effects/kmpmp_update_global_lists_effects.txt, src/common/scripted_triggers/kmpmp_united_country_triggers.txt
=> reapply scandinavian united country buff

src/common/decrees/kmpmp_decrees.txt
=> removed sol from migration edict

src/events/law_events/00_kmpmp_unable_to_enact_events.txt
try to fix with adding an "after" block and removing the state variable
Closes #333
=> fix vanilla unable to enact event

src/events/00_kmpmp_krakatoa_events.txt
=> execute krakatoa tsunami effect just once

src/common/journal_entries/kmpmp_05_request_recognition.txt, src/localization/english/replace/sphere_of_influence_2_l_english.yml, src/localization/german/replace/sphere_of_influence_2_l_german.yml
=> fix earning recognition tooltip

src/common/journal_entries/kmpmp_super_germany_JE.txt, src/localization/english/kmpmp_super_germany_l_english.yml, src/localization/german/kmpmp_super_germany_l_german.yml
=> #276 German-Austrian Content

src/common/static_modifiers/kmpmp_player_boost_modifiers.txt
=> 366 Art of Deal Buff

src/common/history/buildings/kmpmp_buildings.txt, src/common/interest_group_traits/kmpmp_00_devout_traits.txt
=> 365 Japan Changes

src/common/company_types/kmpmp_companies.txt, src/common/interest_group_traits/kmpmp_00_industrialists_traits.txt, src/common/interest_group_traits/kmpmp_industrialists_traits.txt, src/common/laws/kmpmp_00_governance_principles.txt, src/common/modifier_type_definitions/kmpmp_modifier_types.txt, src/common/static_modifiers/kmpmp_player_boost_modifiers.txt, src/common/static_modifiers/kmpmp_united_country_modifiers.txt, src/common/trigger_localization/kmpmp_trigger_localization.txt, src/localization/english/kmpmp_companies_l_english.yml, src/localization/english/kmpmp_modifiers_l_english.yml, src/localization/english/kmpmp_triggers_l_english.yml, src/localization/german/kmpmp_companies_l_german.yml, src/localization/german/kmpmp_modifiers_l_german.yml, src/localization/german/kmpmp_triggers_l_german.yml
- renamed japan company imperial arsenal (duplicate of vanilla name)
- fixed tech requirement for japan company "Genda Shigyo"
- add tax_dividens to nearly all buffs with manufacturing_tax_mult
- fix triggers in law_council_republic
Closes #375
=> fixes and adjustments

src/common/scripted_effects/kmpmp_sick_man_effects.txt, src/events/00_kmpmp_sick_man_events.txt
=> updated claims for completing otto sick man

src/common/history/global/kmpmp_china_buff_global.txt, src/common/journal_entries/kmpmp_china_buff_je.txt, src/common/on_actions/kmpmp_temporary_on_actions.txt, src/events/kmpmp_china_buff_events.txt
=> apply china buff only for ai

src/.metadata/metadata_kmpmp.json, src/.metadata/metadata_kmpmp_test.json, src/.metadata/metadata_kspmp.json
=> update to 1.7.7

src/localization/english/kmpmp_spain_america_l_english.yml, src/localization/german/kmpmp_spain_america_l_german.yml
=> localize mexico-spain modifiers

src/common/diplomatic_actions/kmpmp_36_subjects_grant_own_market.txt, src/common/game_rules/kmpmp_player_protectorate_game_rules.txt, src/common/journal_entries/kmpmp_subject_demobilization.txt, src/common/on_actions/kmpmp_on_actions.txt, src/common/on_actions/kmpmp_player_protectorate_on_actions.txt, src/gui/00_kmpmp_military_formations_panel.gui, src/localization/english/kmpmp_player_protectorate_l_english.yml, src/localization/german/kmpmp_player_protectorate_l_german.yml
- demobilze player protectorates on -100 war support is not working, actually we can't demobilize from script
Closes #388
=> force player protectorates own market

src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt
=> fix powerbloc principle aggressive coordination 3

src/common/technology/technologies/kmpmp_social.txt
=> tech changes

src/common/journal_entries/kmpmp_military_goods_shortage_je.txt, src/common/modifier_type_definitions/kmpmp_00_modifier_types.txt, src/common/on_actions/kmpmp_military_goods_shortage_on_actions.txt, src/common/scripted_effects/kmpmp_military_goods_shortage_effects.txt, src/common/static_modifiers/kmpmp_military_goods_shortage_modifiers.txt, src/localization/english/kmpmp_military_goods_shortage_l_english.yml, src/localization/german/kmpmp_military_goods_shortage_l_german.yml
=> punish military goods shortage

README.md, src/common/script_values/kmpmp_gdp_on_scrip_values.txt, src/common/scripted_guis/kmpmp_gpd_owner_gui.txt, src/gui/00_kmpmp_country_panel.gui, src/localization/english/kmpmp_gdp_owner_l_english.yml, src/localization/german/kmpmp_gpd_owner_l_german.yml
test 378
READMEdman.md
closes #378
=> add mod GDP ownership display

src/common/diplomatic_actions/kmpmp_36_subjects_grant_own_market.txt, src/common/on_actions/kmpmp_player_protectorate_on_actions.txt
- fixes to force own market if overlord is not in power_bloc
Closes #428
=> fix own market for player protectorate

src/common/journal_entries/kmpmp_military_goods_shortage_je.txt, src/common/script_values/kmpmp_military_goods_shortage_values.txt, src/common/scripted_effects/kmpmp_military_goods_shortage_effects.txt, src/common/scripted_guis/kmpmp_military_goods_shortage_gui.txt, src/common/scripted_triggers/kmpmp_military_goods_shortage_triggers.txt, src/localization/english/kmpmp_military_goods_shortage_l_english.yml
- invalidate je instead of complete
- rework effects and triggers
- prepare better explanation
Closes #426
=> invalidate je military goods shortage

src/common/diplomatic_actions/kmpmp_36_subjects_grant_own_market.txt, src/common/on_actions/kmpmp_player_protectorate_on_actions.txt, src/common/scripted_triggers/kmpmp_player_protectorate_triggers.txt, src/common/trigger_localization/kmpmp_player_protectorate_trigger_localization.txt, src/localization/english/kmpmp_player_protectorate_l_english.yml, src/localization/german/kmpmp_player_protectorate_l_german.yml
=> reworked player protectorate own market

src/common/laws/kmpmp_00_economic_system.txt
=> law traditionalism lowered mapi penalty

src/common/diplomatic_actions/kmpmp_02_obligation_actions.txt
=> hide trigger event in "take on debt" tooltip

src/common/decisions/vtm_generic_decisions_disable.txt, src/common/history/buildings/kmpmp_buildings.txt, src/common/history/global/kmpmp_global.txt, src/common/history/military_formations/00_military_formations_europe.txt, src/common/journal_entries/kmpmp_00_dual_monarchy.txt, src/common/journal_entries/kmpmp_three_crowns.txt, src/common/static_modifiers/kmpmp_austria_buff_modifiers.txt, src/common/static_modifiers/kmpmp_german_buff_modifiers.txt, src/events/00_vtm_german_unification.txt, src/localization/english/kmpmp_austria_buff_l_english.yml, src/localization/english/kmpmp_german_buff_l_english.yml, src/localization/german/kmpmp_austria_buff_l_german.yml, src/localization/german/kmpmp_german_buff_l_german.yml
=> Austro Prussian rebalance

src/common/history/buildings/kmpmp_buildings.txt, src/map_data/state_regions/00_west_europe.txt, src/map_data/state_regions/01_south_europe.txt, src/map_data/state_regions/02_east_europe.txt, src/map_data/state_regions/07_south_america.txt, src/map_data/state_regions/08_middle_east.txt, src/map_data/state_regions/09_central_asia.txt, src/map_data/state_regions/11_east_asia.txt, src/map_data/state_regions/12_indonesia.txt, src/map_data/state_regions/13_australasia.txt, src/map_data/state_regions/15_russia.txt
=> 446 rebalance resources to make more conflicts viable

src/common/interest_group_traits/kmpmp_00_armed_forces_traits.txt, src/common/interest_group_traits/kmpmp_armed_forces_traits.txt, src/common/interest_groups/kmpmp_00_armed_forces.txt, src/common/on_actions/kmpmp_temporary_on_actions.txt, src/localization/english/kmpmp_interest_group_traits_l_english.yml, src/localization/english/kmpmp_l_english.yml, src/localization/english/replace/interest_group_traits_l_english.yml, src/localization/german/kmpmp_interest_group_traits_l_german.yml, src/localization/german/kmpmp_l_german.yml, src/localization/german/replace/interest_group_traits_l_german.yml
=> fix german ig army trait

src/common/history/global/kmpmp_merge_cultures_global.txt
if maltese are south_italian gb is forced in the italian unification play
Closes #459
=> fix culture maltese gets corsican

src/events/00_vtm_german_unification.txt
claims only for prussia and austria
Closes #462
=> fix "german idea" claims

src/common/journal_entries/kmpmp_german_content.txt, src/common/on_actions/kmpmp_temporary_on_actions.txt, src/common/static_modifiers/kmpmp_german_content_modifiers.txt, src/localization/english/kmpmp_german_content_l_english.yml, src/localization/german/kmpmp_german_content_l_german.yml
=> add je "Fate in the East"

src/common/script_values/zz_kmpmp_01_power_bloc_values.txt
=> fix power bloc leverage penalties

src/common/journal_entries/kmpmp_00_south_america_migration.txt
=> fix americas migration jes

src/common/journal_entries/kmpmp_adriatic_empire_je.txt, src/common/on_actions/kmpmp_temporary_on_actions.txt, src/common/static_modifiers/kmpmp_adriatic_empire_modifiers.txt, src/localization/english/kmpmp_adriatic_empire_l_english.yml, src/localization/german/kmpmp_adriatic_empire_l_german.yml
=> add je "Adriatic Empire"

src/localization/german/kmpmp_german_french_content_l_german.yml
=> fix german loc for modifier "kmpmp_humiliated_by_the_germans"

src/common/scripted_progress_bars/zz_kmpmp_00_victoria_progress_bars.txt
=> fixed je_earn_recognition progress bar calculation

src/localization/english/kmpmp_military_goods_shortage_l_english.yml, src/localization/german/kmpmp_military_goods_shortage_l_german.yml
=> fix localizations for military goods shortages

src/common/decisions/kmpmp_player_boost_decisions.txt, src/common/decrees/kmpmp_decrees.txt, src/common/defines/kmpmp_00_defines.txt, src/common/history/global/kmpmp_country_buffs_global.txt, src/common/laws/kmpmp_00_distribution_of_power.txt, src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt, src/common/script_values/zz_kmpmp_01_power_bloc_values.txt, src/common/scripted_effects/kmpmp_nation_buff_effects.txt, src/common/scripted_effects/kmpmp_player_boost_effects.txt, src/common/static_modifiers/kmpmp_nation_buff_modifiers.txt, src/common/static_modifiers/kmpmp_player_boost_modifiers.txt, src/localization/english/kmpmp_interfaces_l_english.yml, src/localization/english/kmpmp_l_english.yml, src/localization/english/kmpmp_player_boost_l_english.yml, src/localization/english/kmpmp_script_values_l_english.yml, src/localization/german/kmpmp_interfaces_l_german.yml, src/localization/german/kmpmp_l_german.yml, src/localization/german/kmpmp_player_boost_l_german.yml, src/localization/german/kmpmp_script_values_l_german.yml
- GB debuff "Global Empire"
- law Technocracy: 20% consumption tax cost, +5% education access
- new State alignment "Influential State" - to simplify creation of power blocs in late game
- doubled base assimilation/conversion rate
- doubled assimilation/conversion rate from Decree "National Agenda"
- Vassalization Mandate lvl 2 only grant 20 authority per power bloc memeber instead of 25
Closes #487
=> balance for season 16 part 2

src/common/journal_entries/kmpmp_baby_boom.txt
=> #491 fix je babyboom

src/events/00_vtm_german_unification.txt, src/events/kmpmp_spain_america_events.txt, src/localization/english/kmpmp_spain_america_l_english.yml, src/localization/german/kmpmp_spain_america_l_german.yml
=> #494 fix spain mexico "A mutual beneficial deal"

src/common/country_creation/kmpmp_00_releasable_countries.txt
=> #495 fix liberate amazonia

src/common/buildings/zw_cpc_04_plantations.txt
=> #510 fix bug vanilla british dictate plantations

src/common/journal_entries/kmpmp_ottoman_medium_nation.txt, src/common/scripted_buttons/kmpmp_ottoman_buttons.txt, src/common/scripted_effects/kmpmp_nation_buff_effects.txt, src/localization/english/kmpmp_ottoman_medium_nation_l_english.yml, src/localization/german/kmpmp_ottoman_medium_nation_l_german.yml
=> #501 new je for ottoman switch to medium nation

src/common/journal_entries/kmpmp_00_strike_je.txt, src/common/scripted_triggers/kmpmp_00_strike_triggers.txt
=> #496 je strike completion trigger for incorporated states only

src/common/modifier_type_definitions/kmpmp_modifier_types.txt, src/common/script_values/zz_kmpmp_01_power_bloc_values.txt, src/common/static_modifiers/kmpmp_nation_buff_modifiers.txt, src/localization/english/kmpmp_modifiers_l_english.yml, src/localization/english/kmpmp_script_values_l_english.yml, src/localization/german/kmpmp_modifiers_l_german.yml, src/localization/german/kmpmp_script_values_l_german.yml
=> #498 medium nation buff adds mandate progress

src/common/history/military_formations/00_military_formations_europe.txt
=> #507 add light ships to sweden, portugal, spain

src/common/diplomatic_actions/kmpmp_04_trade_states.txt, src/common/game_rules/kmpmp_game_rules.txt, src/localization/english/kmpmp_trade_states_l_english.yml, src/localization/german/kmpmp_trade_states_l_german.yml
=> #429 add game setting to ignore relations for state trading

src/common/history/global/kmpmp_country_buffs_global.txt, src/common/scripted_effects/kmpmp_nation_buff_effects.txt, src/common/static_modifiers/kmpmp_nation_buff_modifiers.txt
=> #505 gb global empire debuff decaying over 50 years

src/common/diplomatic_actions/kmpmp_04_trade_states.txt
=> #506 on state trade add truce to neighbouring countries

src/common/laws/kmpmp_00_church_and_state.txt, src/common/laws/kmpmp_00_citizenship.txt, src/common/laws/kmpmp_00_distribution_of_power.txt, src/common/laws/kmpmp_00_governance_principles.txt, src/common/laws/kmpmp_00_taxation.txt, src/common/laws/qwf_00_army_model.txt
=> #520 law rebalances

src/common/static_modifiers/kmpmp_00_code_static_modifiers.txt
=> #497 reduce prestige from mobilized armies

src/common/production_methods/kmpmp_11_private_infrastructure.txt
=> #391 lowered workforce for trade centers

src/common/country_creation/kmpmp_00_releasable_countries.txt
=> #525 fix liberate egypt

src/common/modifier_type_definitions/kmpmp_modifier_types.txt, src/common/technology/technologies/kmpmp_military.txt, src/localization/english/kmpmp_modifiers_l_english.yml, src/localization/german/kmpmp_modifiers_l_german.yml
=> #535 add modifier for land battle size

src/common/script_values/zz_kmpmp_01_power_bloc_values.txt
=> #554 fix preserved mandates not applied
